[[ATKmm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95fd021f12c8c4206d5f752117021ec993e22881"
os = "macos"

    [[ATKmm.download]]
    sha256 = "04e5a6a3ef01aa491d6db3078d6b34dd4b253418e96f8657ff5078441b959bc5"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.aarch64-apple-darwin-cxx03.tar.gz"
[[ATKmm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "630452369f807f4e5e6909b31892ffa01848d62a"
os = "macos"

    [[ATKmm.download]]
    sha256 = "c6553f6e2245a05f4cd4503bbfc06f6b5ef17b584b6cf90e7274480fbd8869da"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.aarch64-apple-darwin-cxx11.tar.gz"
[[ATKmm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "859b01d28f26967962a970b6e089e921f1437169"
libc = "glibc"
os = "linux"

    [[ATKmm.download]]
    sha256 = "82570322379a92c472c8018499a4864bbeb4d7b7cc2b25cc40e4fbc30b738635"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.aarch64-linux-gnu-cxx03.tar.gz"
[[ATKmm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10adba19da69dcf442188c7c44758141923d6ce4"
libc = "glibc"
os = "linux"

    [[ATKmm.download]]
    sha256 = "dbab7ff89358105936e9145dee5016d278008d3d24f2599c86c55cc1c2d97a4b"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.aarch64-linux-gnu-cxx11.tar.gz"
[[ATKmm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35b83ba4c83fddc4d3d7a3357668d208815b19cf"
libc = "musl"
os = "linux"

    [[ATKmm.download]]
    sha256 = "bb954d3b273b46a04d688bbe1fb7e04d3c3b170f0a690f4c694499a2c679c6b1"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.aarch64-linux-musl-cxx03.tar.gz"
[[ATKmm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cb2462c16d39ddb8f86fe013a3d32e26a5bd5f2"
libc = "musl"
os = "linux"

    [[ATKmm.download]]
    sha256 = "7099d7dda76606aca8b7456758373230da7ac2a0032412ddf60bd66a5160b747"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.aarch64-linux-musl-cxx11.tar.gz"
[[ATKmm]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9b3081be6750ce1dc72b70f95254b0ca523862f9"
libc = "glibc"
os = "linux"

    [[ATKmm.download]]
    sha256 = "ceada89195ad4f928a95ec66dd8c1d3284c73c8776fd079aad4a974297a019b8"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ATKmm]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9cae3c26179a8ae377fe621d732136c6c62c332"
libc = "glibc"
os = "linux"

    [[ATKmm.download]]
    sha256 = "99a9ad543b9da1856266b3f5eec79212c30d67f529f2a4b921914d79dab76bd7"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ATKmm]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de6865e5e1f64abe31b5f5162fc4b4ace3d39780"
libc = "musl"
os = "linux"

    [[ATKmm.download]]
    sha256 = "8a4906400d6dc4c25f4cfb584284775392865963dcff57fa083b85d9205232ac"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ATKmm]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "904c14538e878ebd676cf704318ef592f0826adb"
libc = "musl"
os = "linux"

    [[ATKmm.download]]
    sha256 = "c0adcae50d85acae3fbb6b8b672ba832bd28a4a10fd967cdb749c7b9a482ba0d"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ATKmm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa32b83ea4803709247ee131fcc91405e25cd997"
libc = "glibc"
os = "linux"

    [[ATKmm.download]]
    sha256 = "1adb8395feef04840c82b8398b160f0c2a81cebc927c1978e1d62aae0d718c3a"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ATKmm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b920e98cecae23b42c311af07632e6224a296ee"
libc = "glibc"
os = "linux"

    [[ATKmm.download]]
    sha256 = "756de742023c58efa49746eb0b16ca6d8f32ea3f95934d64b912c38de87b4387"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ATKmm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a60e3e7df46a3ae3639512f4e55e36518413693"
libc = "musl"
os = "linux"

    [[ATKmm.download]]
    sha256 = "b762d3fbd94b79033a5100cf7e6f9896fe302d9acaca931fe8ef9e80f0c89606"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ATKmm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6dd2889ea7df2c30d02fb8eaf484042be695a563"
libc = "musl"
os = "linux"

    [[ATKmm.download]]
    sha256 = "4b02f885d1507d53034253c17d0f4946bf80d3454c1b8113ad43a1f023d345e8"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ATKmm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "579d05536c5f0657a74a69fc1086b0b4e6cadf06"
libc = "glibc"
os = "linux"

    [[ATKmm.download]]
    sha256 = "b6de5c5878664720e9f0e7e42f3edfcc17f8323ac10f357e49ffeab6a2f92c75"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.i686-linux-gnu-cxx03.tar.gz"
[[ATKmm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e854d76dd763b41e2ef6d49e6e0997627c05d0fe"
libc = "glibc"
os = "linux"

    [[ATKmm.download]]
    sha256 = "bc2cb970238923f1a71ed69904ae5dc1410be1c30f8d8a4e6e92a3ea3c88b8e8"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.i686-linux-gnu-cxx11.tar.gz"
[[ATKmm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4061a1a558c70c4726a729d17c990b1c7cca8a93"
libc = "musl"
os = "linux"

    [[ATKmm.download]]
    sha256 = "d45335bbcf1dc73feabe2f4190f0f10520e6e2e019ff54c8396eb99af63e63e5"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.i686-linux-musl-cxx03.tar.gz"
[[ATKmm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4bf41d363c6202378d6e1e531144f26bd2d9d78"
libc = "musl"
os = "linux"

    [[ATKmm.download]]
    sha256 = "efd502a18aecebdfbf1865664bd5e6dbb269220976f8e54b0473a86c1d846061"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.i686-linux-musl-cxx11.tar.gz"
[[ATKmm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cd51fb908b520bf4b71a53050339217fb7a930e"
os = "windows"

    [[ATKmm.download]]
    sha256 = "000ff9f5368b6262673cb7baf4e7f7b55b4c743170e3c9d9847ca9aa140256a3"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.i686-w64-mingw32-cxx03.tar.gz"
[[ATKmm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6e082afd2deeb4259e4cd44c8cbbb99d49c6b42"
os = "windows"

    [[ATKmm.download]]
    sha256 = "411d06823eb6dcc307821a68a8fba08868cefaf531318cf9f0a9f9b64f2d7f36"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.i686-w64-mingw32-cxx11.tar.gz"
[[ATKmm]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a2ab730e64364513eb492ac87ebef39986f5386"
libc = "glibc"
os = "linux"

    [[ATKmm.download]]
    sha256 = "1bd07d61dc783d57bbfd39fd4c27ae1bbdadb9fe028a0bdafcb80f4f3cf04201"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ATKmm]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "352803176190948794f6e3a536b8b42b65e0a402"
libc = "glibc"
os = "linux"

    [[ATKmm.download]]
    sha256 = "53f95f876ceaa8a189a7d80164e540553fa7baa5d3936b49972907b95e30c52b"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ATKmm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a51556ad6463295eaf37a6934777b5a0b3cb01a6"
os = "macos"

    [[ATKmm.download]]
    sha256 = "df208f51a14679cbe5b76b38408c81a13314b2cd8f608e5fbdf822b08a4b5e91"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.x86_64-apple-darwin-cxx03.tar.gz"
[[ATKmm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c954a177a86b1ef46a2619f344565e67ec299b1e"
os = "macos"

    [[ATKmm.download]]
    sha256 = "57fce84b36a45585df7aea3a63f5bb735dc306748ee9d27570b70829fb73b43b"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.x86_64-apple-darwin-cxx11.tar.gz"
[[ATKmm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0abaabe208d13719a05fc5a1e86591a42dadbcc"
libc = "glibc"
os = "linux"

    [[ATKmm.download]]
    sha256 = "b1fedd480bed007238e72fd4c6329b197acf9c03d33bb8a7765dccac09ce7383"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.x86_64-linux-gnu-cxx03.tar.gz"
[[ATKmm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb9d077cee34643e9434f0c69b3c3bbc0da30a18"
libc = "glibc"
os = "linux"

    [[ATKmm.download]]
    sha256 = "60ba80d2d6a6a252a642dea7889e720b85105d020add23c40f0c92d8a71da948"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.x86_64-linux-gnu-cxx11.tar.gz"
[[ATKmm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a34d5778972d0aa6b3a1ca9f9d6ffc7844145ddd"
libc = "musl"
os = "linux"

    [[ATKmm.download]]
    sha256 = "95a0e92061e2cc39b17c67b691b194a4fee20592b4a023cb3a436f886e82cb8b"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.x86_64-linux-musl-cxx03.tar.gz"
[[ATKmm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bf276a3c9d3bb99720c4f1bc271457e05d3b767"
libc = "musl"
os = "linux"

    [[ATKmm.download]]
    sha256 = "88cff17e92aa331bce15b6ef599419e135a0397201030afe0da91c3934297d9b"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.x86_64-linux-musl-cxx11.tar.gz"
[[ATKmm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71c214c6e5946088d3072134152d1d87d37c9985"
os = "freebsd"

    [[ATKmm.download]]
    sha256 = "ba6f27bc8a5dee90d159ce524e90fceb08512e8405b5e8485865780ebd43935f"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.x86_64-unknown-freebsd-cxx03.tar.gz"
[[ATKmm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89112131cc6a6d69b88c801397107e707302cfd7"
os = "freebsd"

    [[ATKmm.download]]
    sha256 = "3168a360c6d008182f6338078d59bc01663b360099d847c51568b54cc35a268f"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.x86_64-unknown-freebsd-cxx11.tar.gz"
[[ATKmm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2228b58ebb152bc5b731047777d5c7dab30b9a43"
os = "windows"

    [[ATKmm.download]]
    sha256 = "ed5e045fd0c1cbdc2757ea587eb07ee18d14ddde6d5b877f1a2f197cbf781217"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[ATKmm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf2a0a10858e42ca04a284234f24bd33b86be2fa"
os = "windows"

    [[ATKmm.download]]
    sha256 = "c55e6b6cfd8c1ac49aa6cc01807902240188679e89c710d7012a97145bad4ea2"
    url = "https://github.com/JuliaBinaryWrappers/ATKmm_jll.jl/releases/download/ATKmm-v2.36.2+0/ATKmm.v2.36.2.x86_64-w64-mingw32-cxx11.tar.gz"
